config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :patients
  resources :doctors do 
    resources :appointments
  end

  namespace :admin do 
    resources :doctors do
      
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :doctor
    belongs_to :patient

    scope :by_date, ->{order(appointment_date: :asc)}
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :appointments
    has_many :patients, through: :appointments
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments
    has_many :doctors,  through: :appointments
end

app/controllers/admin/doctors_controller.rb
class Admin::DoctorsController < ApplicationController
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

    def index
        @doctor = Doctor.find_by(id: params[:doctor_id])
        if params[:doctor_id]
            @appointments = Doctor.find_by(id: params[:doctor_id]).appointments.by_date
            redirect_to doctors_path unless @appointments
        else
            @appointments = Appointment.all
        end
    end

    def show
        @appointment = Appointment.find(params[:id])
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
   

    def index
        @doctors = Doctor.all
    end

    def show
        
        @doctor = Doctor.find(params[:id])
        
        render :layout => "doctor2"
    end

    def new
        @doctor = Doctor.new

    end
    def edit
        @doctor = Doctor.find(params[:id])
    end

  
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

    def show
        @patient = Patient.find(params[:id])
    end
end

app/helpers/admin/doctors_helper.rb
module Admin::DoctorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/index.html.erb
<% if @doctor %>
<h2>Doctor: <%= @doctor.name %></h2>
<% end %>
<% @appointments.each do |appointment| %>
    <h4>Patient: <%= appointment.patient.name %></h4>
    <%= appointment.appointment_date.strftime("%H:%M %A, %B %d") %>
<% end %>

app/views/appointments/show.html.erb
<h2><%= @appointment.appointment_date %></h2>
<h4>Appointment for:<%= @appointment.patient.name %></h4>
<h5>With Doctor: <%= @appointment.doctor.name %></h5>

app/views/doctors/_form.html.erb
<%= form_for @doctor do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br />
    <%= f.submit %>
<% end %>

app/views/doctors/edit.html.erb
<%= render 'form' %>

app/views/doctors/index.html.erb
<h1>List of current Doctors</h1>
<% @doctors.each do |doctor| %>
    <p><%= link_to doctor.name, doctor_path(doctor) %></p>
<% end %>

app/views/doctors/new.html.erb
<%= render 'form' %>

app/views/doctors/show.html.erb
<h3><%= @doctor.name %>'s Patients: </h3>
<% @doctor.patients.each do |patient| %>
    
<%= render partial: 'patients/patient', locals: {patient: patient} %>
<% end %>


<%= link_to "Appointments", doctor_appointments_path(@doctor) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorsOffice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/doctor.html.erb
<!DOCTYPE html>
    <head>
        <link rel="stylesheet" type="text/css" href="doctorstyles.css" />
        <title>Doctor</title>
    </head>
    <body>
    <%=yield %>
    </body>
</html>

app/views/layouts/doctor2.html.erb
<!DOCTYPE html>
    <head>
        <link rel="stylesheet" type="text/css" href="/doctor2styles.css">
        <title>Welcome to the Doctors</title>
    </head>
    <body>
        <%= yield%>
    </body>
</html>

app/views/patients/_patient.html.erb
Patient Name: <%= patient.name %>
<% patient.appointments.each do |appointment| %>
    <p><%= link_to appointment.appointment_date, appointment_path(appointment) %></p>
<% end %>

app/views/patients/show.html.erb
<%= render partial: 'patient', locals: {patient: @patient} %>